[[main]]
    name = "Home"
    url = ""
    weight = -110

[[main]]
    name = "About"
    url = "about"
    weight = -109

[[social]]
    name = "github"
    type = "social"
    weight = 1
    url = "https://github.com/jlabonski"

[[social]]
    name = "rss"
    weight = 4
    url = "index.xml"
