baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Jeffrey Labonski's Web Log"

[params]
	  #scheme = "dark" # light, dark, gray or preference
      since = "1978"

[module]
  [[module.imports]]
    #path = "github.com/bake/solar-theme-hugo"
    path = "github.com/chipzoller/hugo-clarity"